# Generated by Django 5.0.2 on 2024-03-25 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, null=True)),
                ('phone_number', models.CharField(max_length=12)),
                ('delivery_address', models.CharField(max_length=200)),
                ('is_paid', models.BooleanField(default=False)),
                ('total', models.PositiveIntegerField()),
                ('order_id', models.CharField(max_length=200, null=True)),
                ('payment', models.CharField(choices=[('cod', 'cod'), ('online', 'online')], default='cod', max_length=200)),
                ('status', models.CharField(choices=[('order-placed', 'order-placed'), ('intransit', 'intransit'), ('dispatched', 'dispatched'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], default='order-placed', max_length=200)),
                ('user_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basket_item_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.basketitem')),
                ('order_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaseitems', to='shop.order')),
            ],
        ),
    ]
