# Generated by Django 5.0.2 on 2024-06-03 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
